[package]
name = "wg"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/wg.rs"

[dependencies]
nalgebra = "0.31.4"
tokio = { version = "1.29.1", features = ["full"] }
noise = { version = "0.8.2", features = ["images"] }